spring:
  application:
    name: exchange-service

bybit:
  domain: TESTNET
  api-key: EkZNuyjyt3Pr6Ieqa8
  api-secret: RnwoqKHgiKkiCvk7w5t5B0BA0DSyF7cAYoCH
  ws-url: wss://stream-testnet.bybit.com/v5/public/spot

bot:
  endpoints:
    - name: sma
      url: 'http://localhost:8081'
    - name: rsi
      url: 'http://localhost:8082'

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info,metrics"
  endpoint:
    prometheus:
      access: unrestricted
  prometheus:
    metrics:
      export:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        http.client.requests: true
        bot.decision.latency.ms: true
        bot.order.submit.latency.ms: true
        bot.order.ack.latency.ms: true
        bot.e2e.latency.ms: true
        venue.bybit.create_order.ms: true
      percentiles:
        bot.decision.latency.ms: 0.5,0.95,0.99
        bot.order.submit.latency.ms: 0.5,0.95,0.99
        bot.order.ack.latency.ms: 0.5,0.95,0.99
        bot.e2e.latency.ms: 0.5,0.95,0.99
        venue.bybit.create_order.ms: 0.5,0.95,0.99